spring:
  security:
   oauth2:
     client:
       registration:
         github:
            clientId: ${GITHUB_CLIENTID}
            clientSecret: ${GITHUB_CLIENTSECRET}
            
server:
  tomcat:
    use-relative-redirects: true
        